steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp:latest', '-t', 'gcr.io/$PROJECT_ID/myapp:$BUILD_ID', '.']
  id: 'build-image-myapp'
  waitFor: ['-']
images:
- 'gcr.io/$PROJECT_ID/myapp:latest'
- 'gcr.io/$PROJECT_ID/myapp:$BUILD_ID'
#- 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA'

# steps:
# - name: 'node:$_NODE_VER'
#   entrypoint: 'npm'
#   args: ['install']
#   id: 'nodeNpmInstall'